language: ruby

dist: trusty
sudo: false

rvm:
  - 1.8.7
  - 2.4.1
  - 2.3.4
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2

matrix:
  include:
    # Rails 5.x only supports 2.2+
    - rvm: 2.4.1
      env: RAILS_VERSION=master
    - rvm: 2.4.1
      env: RAILS_VERSION=5-0-stable
    - rvm: 2.4.1
      env: RAILS_VERSION=5.1.0

branches:
  only:
    - master
    - staging
